### ISSUE TITLE
Incorrect JSON value rendered for inherited objects  

### ISSUE THREAD

**Issue by zdne** [apiaryio/boutique.js#56]
Given following blueprint / MSON

```apib
# MSON Playground

# GET /1
+ response 200 (application/json)
    + attributes (B)

# Data Structures
# A 
- type: a

# B (A)
- type: b
```

The output application/json for `B` is **incorrectly**

```json
{
  "type": "a"
}
```

instead of:

```json
{
  "type": "b"
}
```

**Comment by zdne** [comment]
Also related https://github.com/apiaryio/mson/issues/28

**Comment by honzajavorek** [comment]
Didn't dig deeper, but is this Boutique's bug or Drafter's? Because Boutique doesn't know anything about inheritance and completely relies on expanded AST it gets from Drafter.

**Comment by kylef** [comment]
Going to close this issue since Boutique has been replaced with Drafter. This bug has been resolved (or never existed) in Drafter.
