### ISSUE TITLE
Boutique is not asynchronous

### ISSUE THREAD

**Issue by LinusU** [apiaryio/boutique.js#57]
This library requires the user to supply a callback that will return the result, yet the callback will always be called before the function returns. This is very confusing and breaks some assumptions that most users do when they see a function that accepts a callback.

In Node.js a callback is generally used when the function needs to do **asynchronous io** (e.g. hitting disk or the network). This module dosen't do any io at all and that is why the callback is called before the function returns.

The correct usage for this function would thus be:

```javascript
var body = boutique.represent({ ast: ast, contentType: 'application/json' })
```

Proof:

```javascript
var boutique = require('boutique')
var ast = {"types":[{"name":null,"typeDefinition":{"typeSpecification":{"name":"object"}},"sections":[{"class":"memberType","content":[{"class":"property","content":{"name":{"literal":"id"},"valueDefinition":{"values":[{"literal":"1"}],"typeDefinition":{"attributes":["required"]}}}},{"class":"property","content":{"name":{"literal":"name"},"valueDefinition":{"values":[{"literal":"A green door"}]}}},{"class":"property","content":{"name":{"literal":"price"},"valueDefinition":{"values":[{"literal":"12.50"}],"typeDefinition":{"typeSpecification":{"name":"number"}}}}},{"class":"property","content":{"name":{"literal":"tags"},"valueDefinition":{"values":[{"literal":"home"},{"literal":"green"}]}}},{"class":"property","content":{"name":{"literal":"vector"},"valueDefinition":{"typeDefinition":{"typeSpecification":{"name":"array"}}},"sections":[{"class":"memberType","content":[{"class":"value","content":{"valueDefinition":{"values":[{"literal":"1"}]}}},{"class":"value","content":{"valueDefinition":{"values":[{"literal":"2"}]}}},{"class":"value","content":{"valueDefinition":{"values":[{"literal":"3"}]}}}]}]}}]}]}]}

boutique.represent({ ast: ast, contentType: 'application/json' }, function (err, body) {
  if (err) throw err

  console.log('IN CALLBACK')
})

console.log('NEXT ROW')
```

**Comment by honzajavorek** [comment]
The library doesn't do any async io as of now indeed, but was written with async io in mind. It would be very hard to introduce it later when we'd realize we need to touch something asynchronous. It's also because of async stack we have - e.g. passing errors vs. throwing them as exceptions, etc.

Basically, I agree with your findings, but I don't see why it's such a problem. This way the library can manage more in the future without breaking the interface.

**Comment by LinusU** [comment]
I don't see how doing any io would be in the scope of boutique but you have a fair point. How about exposing `representSync` as well for when the user wants a synchronous response? I also feel that `represent` should call the callback in the next tick as to not [release zalgo](http://blog.izs.me/post/59142742143/designing-apis-for-asynchrony).

This could be the implementation of `represent`:

```javascript
function represent(options, cb) {
  setImmediate(function () {
    var result

    try {
      result = representSync(options)
    } catch (err) {
      return cb(err)
    }

    return result
  })
}
```

**Comment by honzajavorek** [comment]
I agree something like `representSync` and some tuning of the async interface so it's more *async-ish* could be useful.

**Comment by zdne** [comment]
Hey @LinusU we are currently rewriting rewriting boutique into C++ (as part of the Drafter) to also offer its functionality to other languages but Node.js. As such I would like to avoid any updates to boutique.js

**Comment by LinusU** [comment]
Thats cool :sunglasses:

**Comment by kylef** [comment]
I'm going to close this issue off since the functionality from Boutique.js has been moved to [drafter](https://github.com/apiaryio/drafter). The JavaScript binding for Drafter ([protagonist](https://github.com/apiaryio/protagonist)) provides asynchronous parsing of API Blueprint.
