### ISSUE TITLE
Idea: Fake empty values

### ISSUE THREAD

**Issue by honzajavorek** [apiaryio/boutique.js#6]
We could [fake](https://github.com/marak/Faker.js/) values in case real examples are missing and we are rendering e.g. JSON, where the values are really necessary (in contrast to, let's say, JSON Schema).

Current behavior renders `null` values. With faking being implemented, there would be something like `fakeMissingValues` option defaulting to `false`, which would switch Boutique to the mode in which it would produce arbitrary data (always according to defined type) if examples are missing.

**Comment by kylef** [comment]
I'm going to close this out since Boutique has been replaced by Drafter.
